[fix] 회원가입 비디오 게시 회원 수정 관련 size 검증
everyone-driven-development/miniprojects-2019 pull request #238
Opened 2019-08-31 06:06 UTC by kangmin46

* 회원가입, 유저수정, 비디오게시 등의 사이즈를 검증하는 로직과 테스트코드 추가하였습니다.

2019-08-31 09:25 UTC, Laterality requested changes

2019-08-31 09:25 UTC, Laterality commented on backend/src/main/java/com/woowacourse/edd/application/dto/VideoUpdateRequestDto.java
> +    @Size(max = 255, message = "너무 긴 유튜브 아이디는 안됩니다.")
`VideoSaveRequestDto`에 선언한 상수를 사용하도록 바꾸면 어떨까요?

2019-08-31 09:25 UTC, Laterality commented on backend/src/test/java/com/woowacourse/edd/presentation/controller/BasicControllerTests.java
> +            overSizeContents += "a";
테스트 코드라서 성능에 크게 신경 쓸 필요는 없겠지만 이런 방식으로 문자열을 더하면 길이가 0, 1, 2, ..., `overSizeCount - 1`까지 총 `overSizeCount`개의 `String` 객체가 생성됩니다. 특정 길이의 문자열을 만드는 거라면 다음과 같은 방식은 어떨까요?

```java
    public String getStringOfLength(int length) {
        StringBuilder sb = new StringBuilder(length);
        IntStream.range(0, 5).forEach(i -> sb.append("A"));
        return sb.toString();
    }
```

2019-08-31 09:25 UTC, Laterality commented on backend/src/test/java/com/woowacourse/edd/presentation/controller/CommentControllerTests.java
> +        for (int i = 0; i < 256; i++) {
매직넘버를 하드코딩하면 값이 바뀌었을 때(ex. 길이 제한을 100자로 변경) 변경하기 어려울 것 같은데요, 엔티티나 Dto의 길이를 상수로 분리하고 이를 사용하도록 변경해보면 어떨까요? 256 대신 `CONTENTS_LENGTH_MAX + 1`과 같은 방식으로 표현하면 256이 어떤 의미를 갖는지 더 명확히 표현할 수 있을 것 같아요.

2019-08-31 17:31 UTC, Conatuseus reviewed
에단이 리뷰 잘해줘서 공백제거나, 매직넘버 밖에 리뷰할 게 없었네요ㅎㅎ

2019-08-31 17:31 UTC, Conatuseus commented on backend/src/main/java/com/woowacourse/edd/application/dto/VideoSaveRequestDto.java
> +    public static final String OVER_SIZE_YOUTUBEID_MESSAGE =  "너무 긴 유튜브 아이디는 안됩니다.";
공백추가

2019-08-31 17:31 UTC, Conatuseus commented on backend/src/main/java/com/woowacourse/edd/presentation/controller/CommentController.java
> +    public ResponseEntity save(@PathVariable Long videoId, @Valid @RequestBody CommentRequestDto commentRequestDto, HttpSession session) {
RequestBody 어노테이션이 Valid 앞에 있었으면 좋을 것 같아요

2019-08-31 17:31 UTC, Conatuseus commented on backend/src/test/java/com/woowacourse/edd/presentation/controller/BasicControllerTests.java
> +
불필요한 공백 제거 😄

2019-08-31 17:31 UTC, Conatuseus commented on backend/src/test/java/com/woowacourse/edd/presentation/controller/UserControllerTests.java
> +        UserSaveRequestDto userSaveRequestDto = new UserSaveRequestDto(DEFAULT_USER_NAME, getOverSizeString(256), DEFAULT_USER_PASSWORD, DEFAULT_USER_PASSWORD);
매직넘버 상수화하면 좋을 것 같아요

2019-09-02 06:02 UTC, heebong commented on backend/src/main/java/com/woowacourse/edd/domain/User.java
> +import javax.validation.constraints.Size;
이거 필요한가여??

2019-09-02 06:39 UTC, merged